Repository fossasia/susi_android, pull requests merged in 2018-07, with the labels that each got.

#1472 feat: Make api calls to the smart speaker
  README.md
  app/build.gradle
  app/src/main/java/org/fossasia/susi/ai/data/DeviceModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/contract/IDeviceModel.kt
  app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
  app/src/main/java/org/fossasia/susi/ai/device/DevicePresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/contract/IDevicePresenter.kt
  app/src/main/java/org/fossasia/susi/ai/rest/clients/DeviceClient.java
  app/src/main/java/org/fossasia/susi/ai/rest/services/DeviceService.java
Labels: smart speaker

#1492 Fixed app crash on tapping examples (Fixed #1480)
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
  app/src/main/res/layout/fragment_skill_details.xml
Labels: crash-fix

#1497 fix: tabletype responses are fetched from history
  app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt
  app/src/main/java/org/fossasia/susi/ai/chat/ParseTableSusiResponse.kt
  app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/contract/IChatModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/db/ChatArgs.kt
  app/src/main/java/org/fossasia/susi/ai/data/model/TableItem.java
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Action.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Body.kt
  app/src/main/res/layout/table_item.xml
  app/src/main/res/layout/table_recylcer_item.xml
Labels: crash-fix

#1533 feat: make a basic device connection
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/WifiViewHolder.java
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectView.kt
  app/src/main/res/layout/layout_wifi_item.xml
  app/src/main/res/values/strings.xml
Labels: Work in progress

#1537 fix: receiver null error
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
  app/src/main/res/values/strings.xml
Labels: Priority: HIGH

#1522 Add groups at the bottom of Skills Listing page (Fixed #1519)
  app/src/main/java/org/fossasia/susi/ai/dataclasses/SkillsBasedOnMetrics.kt
  app/src/main/java/org/fossasia/susi/ai/helper/SimpleDividerItemDecoration.java
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillMetricsAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/viewholders/SkillGroupViewHolder.java
  app/src/main/res/drawable/ic_right_facing_arrow.xml
  app/src/main/res/drawable/rv_divider.xml
  app/src/main/res/layout/item_feedback.xml
  app/src/main/res/layout/item_skill_group_list.xml
  app/src/main/res/values/dimens.xml
Labels: review

#1576 Removed unused file SkillGroupAdapter.kt (Fixed #1575)
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillGroupAdapter.kt
Labels: review

#1572 Use same text size for displaying error messages for skills listing fragment (Fixed #1566)
  app/src/main/res/layout/fragment_skill_listing.xml
Labels: review

#1538 feedback for the responses sent only once
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.java
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.java
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/TableViewHolder.java
Labels: review

#1573 Show appropriate message when there are no skills for a particular group (Fixed #1565)
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/contract/IGroupWiseSkillsView.kt
  app/src/main/res/layout/fragment_group_wise_skill_listing.xml
  app/src/main/res/values/strings.xml
Labels: review

#1550 Load skill details when a skill card in GroupWiseSkillsFragment is clicked (Fixed #1549)
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/viewholders/SkillViewHolder.java
Labels: review

#1571 Use appropriate action bar titles (Fixed #1567)
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
Labels: review

#1599 Add newest and top gaming skills to skills listing page (Fixed #1587)
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metrics.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
  app/src/main/res/values/strings.xml
Labels: review

#1603 refactor: Remove redundant semi colons from DeviceConnectFragment.kt (Fixed #1602)
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
Labels: review

#1606 Set CATEGORIES not clickable (Fixed #1605)
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillMetricsAdapter.kt
Labels: review

#1604 Improve UI of skill cards (Fixed #1520)
  app/src/main/java/org/fossasia/susi/ai/helper/CircleTransform.java
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/viewholders/SkillViewHolder.java
  app/src/main/res/layout/item_skill.xml
  app/src/main/res/values/dimens.xml
Labels: review
