Repository fossasia/susi_android, pull requests merged in 2019-09, with the labels that each got.

#2369 chore: Update the readme file (https://github.com/fossasia/susi_android/issues/2364)
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/chat.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/connect_to_device.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/devices.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/groupwise_skills.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/help.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/login.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/privacy.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/rating_and_feedback.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/room.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/set_up_wifi.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/settings1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/settings2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/signup.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/skills.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/skills_list.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/skills_menu.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/voice_input.png
Labels: chore

#2371 chore: Add stetho
  app/build.gradle
  app/config.gradle
  app/src/main/java/org/fossasia/susi/ai/MainApplication.kt
  app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt
Labels: dependencies

#2376 fix: Fix margin and paddings in Manage Device page
  app/src/main/res/layout/fragment_music_servers.xml
Labels: fix

#2377 chore: Rename ContributionHelp.md to CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: chore
