Repository fossasia/susi_android, pull requests merged in 2019-06, with the labels that each got.

#2231 fix: Settings and menu mal function fixed
  app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
Labels: fix

#2247 fix: Fix the bug in the try button of skill details page
  app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
Labels: fix

#2236 fix: unclickable mic or send icon in chat activity
  app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
Labels: fix

#2233 fix: Resolve skill details page contraction
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
  app/src/main/res/layout/fragment_skill_listing.xml
Labels: fix

#2230 fix: Back press in login activity handled
  app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
Labels: fix

#2248 fix: Fix voice commands actions in voice prompt window
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/VoiceCommandsAdapter.kt
Labels: fix

#2202 feat: Voice search implemented on skills listing
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
  app/src/main/res/drawable/ic_settings_voice_black_24dp.xml
  app/src/main/res/menu/skills_activity_menu.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2232 feat: Implement the feature to redirect to login page to rate skills
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsPresenter.kt
  app/src/main/res/values/strings.xml
Labels: feature

#2256 fix: hotword detection problem after speech recongnition fails
  app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
Labels: fix

#2257 fix: Toast message in rating susi response
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/TableViewHolder.kt
Labels: fix

#2259 fix: Increase voice detection time in voice message query
  app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
Labels: fix

#2203 fix: Fixed malfunction of settings fragment
  app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
  app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
Labels: fix

#2262 fix: Run speech recognition in default language
  app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
Labels: fix

#2253 fix: Fix smart speaker connectivity problem during different wifi connection of device
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
Labels: fix

#2273 fix: Change http to https to avoid connection errors
  app/src/main/java/org/fossasia/susi/ai/rest/clients/LocationClient.kt
  app/src/main/java/org/fossasia/susi/ai/rest/clients/WebSearchClient.kt
Labels: fix

#2263 fix: Connect smart speaker to open wifi
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/network_security_config.xml
Labels: fix

#2270 chore: refactor rateskill code in viewholders
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MessageViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/TableViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/YoutubeVideoViewHolder.kt
Labels: chore

#2267 feat: Add room feature
  app/src/main/java/org/fossasia/susi/ai/data/contract/IRoomModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/device/RoomModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/model/RoomsAvailable.kt
  app/src/main/java/org/fossasia/susi/ai/dataclasses/AddDeviceQuery.kt
  app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/recycleradapters/RoomsAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectView.kt
  app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/GetAddDeviceResponse.kt
  app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.kt
  app/src/main/res/drawable/ic_add_24dp.xml
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/layout/fragment_device_connect.xml
  app/src/main/res/layout/room_layout.xml
  app/src/main/res/layout/room_recycler_layout.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2264 feat: Resend message
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MessageViewHolder.kt
  app/src/main/res/drawable/ic_resend.xml
  app/src/main/res/layout/item_user_message.xml
Labels: feature

#2281 fix: Remove excess access token occurrence
  app/src/main/java/org/fossasia/susi/ai/dataclasses/AddDeviceQuery.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
  app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt
Labels: fix

#2279 feat: Add location of the device
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
Labels: feature

#2276 feat: Display connected devices
  app/src/main/java/org/fossasia/susi/ai/data/contract/IRoomModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/device/RoomModel.kt
  app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
  app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/ConnectedDeviceFragment.kt
  app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/ConnectedDevicePresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/adapters/ConnectedDevicesAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/contract/IConnectedDevicePresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/contract/IConnectedDeviceView.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ConnectedDevicesResponse.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Device.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Location.kt
  app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.kt
  app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
  app/src/main/res/layout/fragment_connected_device.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_settings.xml
Labels: feature

#2261 feat: Order feedback by date
  app/src/main/java/org/fossasia/susi/ai/skills/feedback/FeedbackActivity.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt
Labels: feature

#2288 fix: Clicking on room name redirect to connected device fragment
  app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/recycleradapters/RoomsAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
Labels: fix
