Repository fossasia/susi_android, pull requests merged in 2019-05, with the labels that each got.

#2173 fix: added ripple effect for voice commands
  app/src/main/res/layout/item_voice_commands.xml
Labels: fix

#2153 fix: Changed color to the heading in privacy fragment
  app/src/main/res/layout/fragment_privacy.xml
Labels: fix

#2192 chore: Kotlin version updated
  build.gradle
Labels: chore

#2194 fix: Moved help, privacy, about option from menu to settings
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
  app/src/main/java/org/fossasia/susi/ai/skills/privacy/PrivacyFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
  app/src/main/res/menu/skills_activity_menu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ml-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ta-rIN/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_settings.xml
Labels: fix

#2195 fix: Hyperlinked words in textview instead of whole textview
  app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#2200 feat: Added shimmer effect in Skill List fragment
  app/build.gradle
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
  app/src/main/res/layout/fragment_skill_listing.xml
  app/src/main/res/layout/skill_listing_placeholder.xml
  app/src/main/res/values/colors.xml
Labels: feature

#2204 fix: Contents shown in all reviews page
  app/src/main/java/org/fossasia/susi/ai/skills/feedback/FeedbackActivity.kt
Labels: fix

#2201 fix: Made search, susi icon invisible in stt fragment
  app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
Labels: fix

#2216 chore: bump gradle from 3.3.2 to 3.4.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: chore, dependencies

#2217 chore: Upgraded spotless version to 3.23.0
  app/build.gradle
  app/src/main/java/org/fossasia/susi/ai/MainApplication.kt
  app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
  app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/ChatFeedRecyclerAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/SearchResultsAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/SelectionDialogListAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/TableAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/VerticalRecyclerAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/WebSearchAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MapViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MessageViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/PieChartViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/TableViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/YoutubeVideoViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/chat/contract/IChatPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/chat/search/ChatSearchActivity.kt
  app/src/main/java/org/fossasia/susi/ai/chat/search/adapters/ChatSearchAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
  app/src/main/java/org/fossasia/susi/ai/helper/MapHelper.kt
  app/src/main/java/org/fossasia/susi/ai/login/WelcomeActivity.kt
  app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt
  app/src/main/java/org/fossasia/susi/ai/rest/RetrofitInstance.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/others/LocationResponse.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/others/RelatedTopics.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRating.kt
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/viewholders/SkillViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/settings/SettingsPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/SkillExamplesAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/viewholders/FeedbackViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/viewholders/SkillExampleViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/viewholders/SkillGroupViewHolder.kt
  app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt
Labels: chore

#2197 feat: Toast appears when user rates chat
  app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ml-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ta-rIN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2218 feat: Changed minimum android version to v5.0
  app/config.gradle
Labels: feature

#2215 feat: Search skills in category fragments
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
  app/src/main/res/layout/fragment_group_wise_skill_listing.xml
Labels: feature

#2223 feat: Shimmer effect in groupwise skills
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt
  app/src/main/res/layout/fragment_group_wise_skill_listing.xml
  app/src/main/res/layout/groupwise_skill_listing_placeholder.xml
Labels: feature

#2228 fix: Smart speaker is now connectable
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/DeviceViewHolder.kt
Labels: fix

#2221 feat: Voice search implemented on chat
  app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2229 chore: Release v1.2.0
  app/build.gradle
  app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/DeviceViewHolder.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/values/strings.xml
Labels: chore

#2237 fix: fixed visibility of voice search icon in chat activity and stt fragment
  app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
Labels: fix

#2240 fix: Fixed the crash of signup page in landscape mode
  app/src/main/res/layout-land/activity_sign_up.xml
Labels: fix
