Repository fossasia/susi_android, pull requests merged in 2019-07, with the labels that each got.

#2289 feat: Delete rooms in the device connect fragment
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/recycleradapters/RoomsAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
  app/src/main/res/drawable/ic_delete_black_24dp.xml
  app/src/main/res/layout/room_recycler_layout.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#2285 feat: Add manage device section in settings page
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/susi/ai/device/managedevices/ManageDeviceActivity.kt
  app/src/main/java/org/fossasia/susi/ai/device/managedevices/MusicServersFragment.kt
  app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
  app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
  app/src/main/res/drawable/spotify.png
  app/src/main/res/layout/activity_manage_device.xml
  app/src/main/res/layout/fragment_music_servers.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_settings.xml
Labels: feature

#2296 feat: Enhance the UI of the device card similar to google home
  app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/adapters/ConnectedDevicesAdapter.kt
  app/src/main/res/drawable-hdpi/smart_speaker.jpg
  app/src/main/res/drawable/ic_arrow_right_white_24dp.xml
  app/src/main/res/layout/item_speaker.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2243 feat: Implement remember me option in login screen
  app/build.gradle
  app/config.gradle
  app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
  app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
  app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/login/contract/ILoginPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/login/contract/ILoginView.kt
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2293 chore: Update apk generation and naming convention
  exec/apk-gen.sh
Labels: chore

#2304 chore: Add fastlane metadata screenshots and update readme
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/chat.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/groupwise_skills.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/help.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/login.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/privacy.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/rating_and_feedback.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/settings.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/settings1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/settings2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/signup.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/skills.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/skills_list.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/voice_input.png
Labels: chore

#2297 feat: Enhance SUSI.AI smart speaker connection flow
  app/src/main/java/org/fossasia/susi/ai/data/contract/IDeviceModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/device/DeviceModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/device/DeviceService.kt
  app/src/main/java/org/fossasia/susi/ai/data/device/DeviceServiceImpl.kt
  app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/recycleradapters/RoomsAdapter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/WifiViewHolder.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectView.kt
  app/src/main/java/org/fossasia/susi/ai/rest/responses/others/AddRoomResponse.kt
  app/src/main/java/org/fossasia/susi/ai/rest/services/DeviceApi.kt
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
  app/src/main/res/drawable/border_blue.xml
  app/src/main/res/drawable/border_normal.xml
  app/src/main/res/drawable/ic_delete_blue_24dp.xml
  app/src/main/res/drawable/ic_home_blue_24dp.xml
  app/src/main/res/layout/connect_susiai_speaker.xml
  app/src/main/res/layout/finish_setup_layout.xml
  app/src/main/res/layout/fragment_device_connect.xml
  app/src/main/res/layout/layout_wifi_item.xml
  app/src/main/res/layout/password_layout.xml
  app/src/main/res/layout/room_layout.xml
  app/src/main/res/layout/room_recycler_layout.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_settings.xml
Labels: feature

#2308 chore: Fix typos present in the app
  app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
  app/src/main/res/values/strings.xml
Labels: chore

#2310 chore: Update shimmer dependency
  app/build.gradle
  app/config.gradle
Labels: chore

#2311 feat: Filter skills according to the user choice
  app/src/main/java/org/fossasia/susi/ai/data/GroupWiseSkillsModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/contract/IGroupWiseSkillsModel.kt
  app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillListingModel.kt
  app/src/main/java/org/fossasia/susi/ai/dataclasses/SkillsListQuery.kt
  app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
  app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
  app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsPresenter.kt
  app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
  app/src/main/res/drawable/ic_arrow_downward_blue_24dp.xml
  app/src/main/res/drawable/ic_arrow_upward_blue_24dp.xml
  app/src/main/res/drawable/ic_format_list_bulleted_black_24dp.xml
  app/src/main/res/menu/skills_activity_menu.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2317 fix: Remove filter options from settings page
  app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
Labels: fix

#2316 feat: Update url to show display of connected devices
  app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.kt
Labels: feature

#2322 chore: Update version number
  app/build.gradle
Labels: chore

#2325 chore: Fix the release script
  app/build.gradle
  build.gradle
  circle.yml
Labels: chore

#2326 chore: Baseline master into dev
  app/build.gradle
  build.gradle
  circle.yml
Labels: chore

#2328 chore: Add fastlane metadata
  exec/.gitignore
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/15.txt
  fastlane/metadata/android/en-US/changelogs/16.txt
  fastlane/metadata/android/en-US/changelogs/17.txt
  fastlane/metadata/android/en-US/changelogs/6.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/promoGraphic.png
  fastlane/metadata/android/en-US/images/sevenInchScreenshots/.gitkeep
  fastlane/metadata/android/en-US/images/tenInchScreenshots/.gitkeep
  fastlane/metadata/android/en-US/images/tvScreenshots/.gitkeep
  fastlane/metadata/android/en-US/images/wearScreenshots/.gitkeep
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/en-US/video.txt
Labels: chore

#2329 chore: Update apk script
  exec/apk-gen.sh
Labels: chore
